# Site settings
title: Fast Captions!
email: support@fastcaptions.css
description: > # this means to ignore newlines until "baseurl:"
  Perfect closed captions for your Youtube videos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fastcaptions.cc" # the base hostname & protocol for your site

# Build settings
markdown: kramdown